---  

# Credentials for CVP and EOS Switches
ansible_user: arista
ansible_password: aristay83b # Update password with lab credentials
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)

# AAA
aaa_authentication:
  login:
    default: group atds local

aaa_authorization:
  exec:
    default: group atds local
  commands:
    all_default: local

# Radius Group and Server
aaa_server_groups:
  - name: atds
    type: radius
    servers:
      - server: 192.168.0.1

radius_servers:
  - host: 192.168.0.1
    key: 0207165218120E

ip_radius_source_interfaces:
  - name: Management0
    # vrf: default

# local users
local_users:
  # Username with no password configured
  arista:
    privilege: 15
    role: network-admin
    sha512_password: "$1$4VjIjfd1$XkUVulbNDESHFzcxDU.Tk1"
    ssh_key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQDw05IMB87NmRYiVQZi5kr6Lqm4fyVMkWpRj3eh7iSiEMckeTuF9DLQtIHLOvGWt7R+3WJmsfTJwkm/yDql0tOUda9f5RPr0/CY97xwWipGbqtRW0Tqp8EhkWkpGJL+DUcrczAChovomWFj2PUpq+sjNAVzQEYtkN9ZIF58WwkYYW4AeApIq/AyS0N5ET5t4g9hUYwOcRDlJdykWDfdzdKZV3e4hKi+HejHFS3qnKDKeHavLfOxlSG/PQrL7guAqnH4NOdm9TjJ9l9R0K8MBE3iPLTcMQm5Ek+pDfRiCjhcTyd5XWkR3Rl/tFqiB+Qis/WA31sJTXqgVKodn+vVekUh arista@cleveland-atd-avd-1-30e03f6d"

  # Username with a password
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$1$5O85YVVn$HrXcfOivJEnISTMb6xrJc."

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface: Management0
mgmt_interface_vrf: default

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp:
  servers:
    - name: 192.168.0.1
      iburst: true
      local_interface: Management0

# Domain/DNS
dns_domain: atd.lab

# TerminAttr
daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - 192.168.0.5:9910
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: key
    key: atd-lab
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
